services:
  frontend:
    build:
      context: apps/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks: 
    - peerchess
  backend:
    build:
      context: apps/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks: 
    - peerchess

networks:
  peerchess:
    driver: bridge