export const INIT_GAME = 'INIT_GAME'
export const MOVE = 'MOVE'
export const GAME_OVER = 'GAME_OVER'
export const INVALID_MOVE = 'INVALID_MOVE'
export const WEBRTC_OFFER = "WEBRTC_OFFER";
export const WEBRTC_ANSWER = "WEBRTC_ANSWER"
export const ICE_CANDIDATE = "ICE_CANDIDATE"
export const CLOCK_UPDATE = "CLOCK_UPDATE"
export const MESSAGE = "MESSAGE"
export const INVALID_TURN = "INVALID_TURN"
export const FORFEIT = "FORFEIT"
export const DRAW_OFFER = "DRAW_OFFER"
export const RECONNECT = "RECONNECT"

// Mediasoup
export const GET_ROUTER_RTP_CAPABILITIES = 'GET_ROUTER_RTP_CAPABILITIES';
export const CREATE_WEBRTC_TRANSPORT = 'CREATE_WEBRTC_TRANSPORT';
export const CONNECT_TRANSPORT = 'CONNECT_TRANSPORT';
export const PRODUCE = 'PRODUCE';
export const CONSUME = 'CONSUME';
export const GET_PRODUCERS = 'GET_PRODUCERS';